# Generated by Django 3.2.6 on 2021-08-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.webpage'),
        ),
    ]
