# Generated by Django 3.2.6 on 2021-08-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volkswagen',
            name='company',
        ),
        migrations.DeleteModel(
            name='car',
        ),
        migrations.DeleteModel(
            name='volkswagen',
        ),
    ]
