# Generated by Django 3.2.6 on 2021-08-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('second_app', '0002_auto_20210817_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('b_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_app.car')),
            ],
        ),
    ]
