# Generated by Django 3.2.6 on 2021-08-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.DeleteModel(
            name='continent',
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
