# Generated by Django 3.2.6 on 2021-08-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('third_app', '0002_auto_20210818_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('currency', models.CharField(max_length=250)),
                ('bank', models.CharField(max_length=250)),
            ],
        ),
    ]
